// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, unused_shown_name
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (!kIsWeb) {
    //   return ios;
    // }

    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDydIyZ67EH_BPVoGvuFOELSsz77a7-uj0',
  //   appId: '1:910516599381:web:1e849d6f34aad5d13c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   authDomain: 'udemy-ac28e.firebaseapp.com',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   measurementId: 'G-Z2CQWBK39Q',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpTijuhp-mAgMT9wJYz48X9wKo-6ma8R0',
    appId: '1:1012689313058:android:d4aae83dee1b5c2981197b',
    messagingSenderId: '1012689313058',
    projectId: 'jobapp2021',
    storageBucket: 'jobapp2021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnNmW5vCJACbmKKmW1NIES0-iDDo4b2yQ',
    appId: '1:1012689313058:ios:34b9150de52b284d81197b',
    messagingSenderId: '1012689313058',
    projectId: 'jobapp2021',
    storageBucket: 'jobapp2021.appspot.com',
    iosClientId:
        '1012689313058-sb6ljqkt07h0ktu9n73egj35qmouljh8.apps.googleusercontent.com',
    iosBundleId: 'org.cenixoft.OneHundredEightJobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnNmW5vCJACbmKKmW1NIES0-iDDo4b2yQ',
    appId: '1:1012689313058:ios:34b9150de52b284d81197b',
    messagingSenderId: '1012689313058',
    projectId: 'jobapp2021',
    storageBucket: 'jobapp2021.appspot.com',
    iosClientId:
        '1012689313058-sb6ljqkt07h0ktu9n73egj35qmouljh8.apps.googleusercontent.com',
    iosBundleId: 'org.cenixoft.OneHundredEightJobs',
  );
}
